### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [MarcusVirg/forty#13]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19:
![image](https://user-images.githubusercontent.com/712534/37659212-6e61c49a-2c60-11e8-8525-af03768d5d53.png)

**Comment by MarcusVirg** [comment]
Okay! Thanks for making me aware, I will add the css rule as soon as I test it.

**Comment by MarcusVirg** [comment]
The latest commit should hopefully fix the issue! [57a5dad Commit](https://github.com/MarcusVirg/forty/commit/57a5dad5795926580bb1769c75b32792e875847b)
