### ISSUE TITLE
Is it possible to place the Navigation Links in the header?

### ISSUE THREAD

**Issue by mdhalim** [MarcusVirg/forty#21]
Hey Marcus,

How do I place the navigation links in the Header (navigation bar) and remove the hamburger completely?

Also, if i do remove the hamburger, is it possible to keep it for mobile devices?

**Comment by Frost-Zhao** [comment]
I belive it can be.
Perhaps you need to change the template manually for Implement it.
And if you have seen the "layouts" directory, you will understand.

**Comment by mdhalim** [comment]
Hey thanks mate, I was able to do that by creating my own custom partials of nav.html :)
