### ISSUE TITLE
Please add support for custom CSS

### ISSUE THREAD

**Issue by 0xDedSec42** [MarcusVirg/forty#33]
I'd find it rather useful if I could add some custom CSS. The CSS file you provide is very large and I'd like to change some colors and fonts which I of course can but pushing the changes to a remote Netlify can pull is rather complicated. Sorry for the insanely long sentence.

**Comment by funkydan2** [comment]
Hi @ulfklose, I believe this theme has support for [custom CSS](https://github.com/MarcusVirg/forty/blob/dccea57bd2ed194942080d650671b47b6df4183c/exampleSite/config.toml#L26).

What you need to do is set the `custom_css=[""]` parameter in your config file, and put your CSS file in `/static`.

So, for example, in `config.toml`
```
[params]
    custom_css = ["mystyle.css"]
```
And then put your styles in `/static/mystyle.css`

**Comment by 0xDedSec42** [comment]
Please forgive me, I was blind. It's already in the config.toml from the exampleSite.

**Comment by RoyiAvital** [comment]
Will it work with `bootstrap`'s CSS? Can they co exist (The default and bootstrap)?
