### ISSUE TITLE
Compatibility Issue with Safari and Opera - Incorrect Image Paths

### ISSUE THREAD

**Issue by MarcusVirg** [MarcusVirg/forty#5]
I have heard a few different issues about getting empty images in Safari and Opera (Possibly other browsers). I want to track the issue here and will keep it updated with any solutions I may find.

**Comment by MorseGates** [comment]
I fixed mine after playing around with it. I dropped the blogs image folder into the Static-->img folder along with the other images and commented on the url in the blog pages. that seemed to work for me.
![screen shot 2018-01-14 at 3 27 54 am](https://user-images.githubusercontent.com/32752870/34914252-f2e855d8-f8dc-11e7-9ecb-1499c3ac455d.png)
![screen shot 2018-01-14 at 3 29 41 am](https://user-images.githubusercontent.com/32752870/34914253-f2f498b6-f8dc-11e7-8813-91e260772edb.png)

**Comment by MarcusVirg** [comment]
Great I am glad you got it working! I am guessing the file path is doing some weird things when Hugo is generating the URLs. Is there any chance you have your code on GitHub? I would like to see what your `single.html` file looks like in the `_default` folder.
Here is the default path the theme gives:
```html
<span class="image main"><img src="{{ .Site.Params.baseURL }}/img/blogs/{{ .Params.image }}" alt="" /></span>
```

**Comment by MorseGates** [comment]
Mostly, my changes were with the posts and pages. I did not make any changes to that but this is what my single.html file looks like
![screen shot 2018-01-15 at 12 23 06 pm](https://user-images.githubusercontent.com/32752870/34954572-e85e7896-f9ee-11e7-8055-b2ad437e26d4.png)

**Comment by MorseGates** [comment]
On another subject, do you have suggestions on how to implement code for "Testimonial" and "partners"? I am still fairly new to Hugo.

**Comment by MarcusVirg** [comment]
Yes I am hoping that I will be able to create a more relative URL so I don't have to hard-code in the `/img/blogs` piece in the img source.

Also regarding the Testimonials, I am not very familiar with implementing code for things like that. But I would recommend making a new site with a really simple theme and playing around with Hugo. You can always use third party services to implement things like live stats. If it comes down to it, you can always just use plain HTML and JavaScript alongside the Hugo generation.

**Comment by salim-b** [comment]
Hi, I've ran into the same issue and worked around it by making the image inclusion conditional on the definition of `image` in the YAML header of the respective content like this:

```HTML
{{ if .Params.image }}
<span class="image main"><img src="{{ .Site.BaseURL }}img/{{ .Params.image }}" alt="" /></span>
{{ end }}
```

You'll find my adaptions [here on GitLab](https://gitlab.com/salim_b_public/static_websites/tree/master/opensearch_plugins) if interested.

**Comment by MarcusVirg** [comment]
I have added the conditional in the case that no image file is specified. Thanks for bringing this to my attention!
