### ISSUE TITLE
tel: link

### ISSUE THREAD

**Issue by dstergiou** [MarcusVirg/forty#6]
I tried to add another social icon that points to a phone number by creating this block:

> [[params.footer.social]]
>       icon = "fa-mobile"
>       url= "tel:+46xxxxxxxxx"
>       label = "Call me!"

When i visit the site, i see the following link instead: http://localhost:1313/#ZgotmplZ

Am i doing something wrong, is this a hugo limitation, or have i misunderstood something?

Thanks

**Comment by dstergiou** [comment]
Found the solution, you can edit the template "footer.html" and change:
` <li><a href="{{ .url}}" class="icon alt {{ .icon }}" target="_blank"><span class="label">{{ .label }}</span></a></li>`

to
`<li><a href="{{ .url|safeURL }}" class="icon alt {{ .icon }}" target="_blank"><span class="label">{{ .label }}</span></a></li>
`

**Comment by MarcusVirg** [comment]
I was thinking that was the issue, where Hugo was passing in the value produced by the generator and not the actual HTML in the front matter, but I didn't have time to test it. Thanks for finding a solution to the weird links! I will make this change in the master branch.
